Resources:
  HelloWorldServiceRoleF3F7D8B0:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/HelloWorld/ServiceRole/Resource
  HelloWorld7964D1E8:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beS3Bucket6F2D2B94
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beS3VersionKey8C5A1D96
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beS3VersionKey8C5A1D96
      Handler: app.lambda_handler
      Role:
        Fn::GetAtt:
          - HelloWorldServiceRoleF3F7D8B0
          - Arn
      Runtime: python3.7
    DependsOn:
      - HelloWorldServiceRoleF3F7D8B0
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/HelloWorld/Resource
      aws:asset:path: C:\git\cdk-plus-sam101\app\hello_world
      aws:asset:property: Code
  cdk101api0179353A:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Is this thing even on?
      Name: CDK 101 Service
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Resource
  cdk101apiCloudWatchRoleFBE7E8DB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/CloudWatchRole/Resource
  cdk101apiAccountCCF7698D:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn:
        Fn::GetAtt:
          - cdk101apiCloudWatchRoleFBE7E8DB
          - Arn
    DependsOn:
      - cdk101api0179353A
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Account
  cdk101apiDeployment615BB61C5ea74f2fed93a56f4cb12a6002289672:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId:
        Ref: cdk101api0179353A
      Description: Automatically created by the RestApi construct
    DependsOn:
      - cdk101apihelloGETB6AF509D
      - cdk101apihelloF83A1CE2
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Deployment/Resource
  cdk101apiDeploymentStageprod87FDF63E:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId:
        Ref: cdk101api0179353A
      DeploymentId:
        Ref: cdk101apiDeployment615BB61C5ea74f2fed93a56f4cb12a6002289672
      StageName: prod
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/DeploymentStage.prod/Resource
  cdk101apihelloF83A1CE2:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - cdk101api0179353A
          - RootResourceId
      PathPart: hello
      RestApiId:
        Ref: cdk101api0179353A
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Default/hello/Resource
  cdk101apihelloGETApiPermissionCdkPlusSam101Stackcdk101api7CEBA739GEThelloC6A9B51A:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloWorld7964D1E8
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: cdk101api0179353A
            - /
            - Ref: cdk101apiDeploymentStageprod87FDF63E
            - /GET/hello
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Default/hello/GET/ApiPermission.CdkPlusSam101Stackcdk101api7CEBA739.GET..hello
  cdk101apihelloGETApiPermissionTestCdkPlusSam101Stackcdk101api7CEBA739GEThello962792B2:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - HelloWorld7964D1E8
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":execute-api:"
            - Ref: AWS::Region
            - ":"
            - Ref: AWS::AccountId
            - ":"
            - Ref: cdk101api0179353A
            - /test-invoke-stage/GET/hello
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Default/hello/GET/ApiPermission.Test.CdkPlusSam101Stackcdk101api7CEBA739.GET..hello
  cdk101apihelloGETB6AF509D:
    Type: AWS::ApiGateway::Method
    Properties:
      HttpMethod: GET
      ResourceId:
        Ref: cdk101apihelloF83A1CE2
      RestApiId:
        Ref: cdk101api0179353A
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{ "statusCode": "200" }'
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - ":apigateway:"
              - Ref: AWS::Region
              - :lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - HelloWorld7964D1E8
                  - Arn
              - /invocations
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/cdk101-api/Default/hello/GET/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.78.0,@aws-cdk/assets=1.78.0,@aws-cdk/aws-apigateway=1.78.0,@aws-cdk/aws-applicationautoscaling=1.78.0,@aws-cdk/aws-autoscaling-common=1.78.0,@aws-cdk/aws-cloudwatch=1.78.0,@aws-cdk/aws-codeguruprofiler=1.78.0,@aws-cdk/aws-ec2=1.78.0,@aws-cdk/aws-ecr=1.78.0,@aws-cdk/aws-ecr-assets=1.78.0,@aws-cdk/aws-events=1.78.0,@aws-cdk/aws-iam=1.78.0,@aws-cdk/aws-kms=1.78.0,@aws-cdk/aws-lambda=1.78.0,@aws-cdk/aws-logs=1.78.0,@aws-cdk/aws-s3=1.78.0,@aws-cdk/aws-s3-assets=1.78.0,@aws-cdk/aws-sqs=1.78.0,@aws-cdk/aws-ssm=1.78.0,@aws-cdk/cloud-assembly-schema=1.78.0,@aws-cdk/core=1.78.0,@aws-cdk/cx-api=1.78.0,@aws-cdk/region-info=1.78.0,jsii-runtime=node.js/v12.16.3
    Metadata:
      aws:cdk:path: CdkPlusSam101Stack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beS3Bucket6F2D2B94:
    Type: String
    Description: S3 bucket for asset "1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7be"
  AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beS3VersionKey8C5A1D96:
    Type: String
    Description: S3 key for asset version "1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7be"
  AssetParameters1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7beArtifactHash139A6319:
    Type: String
    Description: Artifact hash for asset "1b996f6c7cebb188ab5a55d4e5d404c553494f94c42ad4a63df06503bd89b7be"
Outputs:
  cdk101apiEndpoint2368BAB0:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: cdk101api0179353A
          - .execute-api.
          - Ref: AWS::Region
          - "."
          - Ref: AWS::URLSuffix
          - /
          - Ref: cdk101apiDeploymentStageprod87FDF63E
          - /
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

